from django.urls import path
from . import views
from . import views_settings

app_name = "front"
urlpatterns = [
     path("", views.LoginView.as_view(), name="top"),
     path("home", views.HomeView.as_view(), name="home"),
     path("board", views.BoardView.as_view(), name="board_menu"),
     path("board/<int:id>",
          views.Board_detailView.as_view(),
          name="board_detail"),
     path("attend",
          views.AttendView.as_view(),
          name="attend"),
     path("attend/<int:year>/<int:month>/",
          views.AttendView.as_view(),
          name="attend"),
     path("attend-info/<int:year>/<int:month>/",
          views.attend_info,
          name="attend_info"),
     path("attend/delete",
          views.AttendDelete.as_view(),
          name="attend_delete"),
     path("attend/<int:year>/<int:month>/<int:day>/",
          views.AttendRegisterDay.as_view(),
          name="attend_register_day"),
     path("Approval", views.ApprovalView.as_view(), name="approval"),
     path("Approval/check/<int:id>",
          views.Approval_checkView.as_view(), name="approval_check"),
     path("Approval/new/<int:id>",
          views.NewApprovalView.as_view(), name="new_approval"),
     path('signup/', views.signupView.as_view(), name='signup'),
     path('signup/register',
          views.signup_Register.as_view(),
          name='signup_register'),
     path("logout", views.LogoutView.as_view(), name="logout"),
     path("tools", views.ToolsView.as_view(), name="tools"),
     path("chat", views.ChatInfo.as_view(), name="chat"),
     path("chat/<room_id>", views.ChatRoom.as_view(), name="chat_room"),
     path("setting", views_settings.SettingView.as_view(), name="setting"),
     path("setting/work_status", views_settings.SettingWorkStatusView.as_view(),
          name="setting_work_status"),
     path("setting/work_status/<int:id>", views_settings.SettingWorkStatusViewById.as_view(),
          name="setting_work_status_by_id"),
     path("setting/holiday", views_settings.SettingHolidayView.as_view(),
          name="setting_holiday"),
     path("setting/user/",
          views_settings.SettingUserView.as_view(),
          name="setting_user"),
     path("setting/approval_format/<int:id>",
          views_settings.SettingApprovalFormatView.as_view(),
          name="setting_approval_format"),
     path("test", views.exec_ajax, name='test'),

]
