version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intra
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql/db:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    expose:
      - "3306"
    restart: always
    healthcheck:
      test: mysqladmin ping -h 0.0.0.0 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: "1s"
      timeout: "10s"
      start_period: "30s"
  app:
    image: django-web:latest
    container_name: App_intra
    environment:
      - DB_NAME=intra
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
    command: sh ./init_app.sh
    volumes:
      - .:/code
    ports:
      - "8085:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
