# Generated by Django 4.1.1 on 2023-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('detail', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('status_complete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'approval',
            },
        ),
        migrations.CreateModel(
            name='Approval_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('detail', models.TextField(null=True)),
            ],
            options={
                'db_table': 'approval_format',
            },
        ),
        migrations.CreateModel(
            name='Approval_format_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_id', models.IntegerField()),
                ('userid', models.CharField(max_length=20, null=True)),
                ('roll', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'approval_format_route',
            },
        ),
        migrations.CreateModel(
            name='Approval_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_id', models.IntegerField()),
                ('userid', models.CharField(max_length=20)),
                ('approved_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'approval_route',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('work_detail', models.CharField(max_length=100, null=True)),
                ('work_status', models.IntegerField(null=True)),
                ('work_start', models.DateTimeField()),
                ('work_end', models.DateTimeField()),
                ('work_off', models.TimeField(default='00:00:00')),
                ('work_time', models.TimeField(default='00:00:00')),
                ('work_overtime', models.TimeField(default='00:00:00')),
                ('carfare', models.IntegerField(default=0)),
                ('memo', models.TextField()),
                ('sysmemo', models.TextField(null=True)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20, null=True)),
                ('created_datetime', models.DateTimeField(null=True)),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('category_id', models.IntegerField(null=True)),
                ('good_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Board_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'board_category',
            },
        ),
        migrations.CreateModel(
            name='Board_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20, null=True)),
                ('created_datetime', models.DateTimeField(null=True)),
                ('detail', models.TextField()),
                ('board_id', models.IntegerField()),
            ],
            options={
                'db_table': 'board_comment',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20, null=True)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('room_id', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('allday', models.BooleanField()),
                ('notification_datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, null=True)),
                ('day_worktime', models.TimeField(default='08:00:00')),
                ('mon_is_holiday', models.BooleanField(default=False)),
                ('tue_is_holiday', models.BooleanField(default=False)),
                ('wed_is_holiday', models.BooleanField(default=False)),
                ('thu_is_holiday', models.BooleanField(default=False)),
                ('fri_is_holiday', models.BooleanField(default=False)),
                ('sat_is_holiday', models.BooleanField(default=True)),
                ('sun_is_holiday', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('name_selection', models.CharField(max_length=3)),
                ('use', models.BooleanField(default=True)),
                ('holiday', models.BooleanField(default=True)),
                ('memo', models.TextField(null=True)),
                ('systemStatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'work_status',
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('userid', 'date'), name='unique_user'),
        ),
    ]
